#!/usr/bin/env bash
# Ralph-Loop hook 01 - SessionStart.
# Reads global rules + project CLAUDE.md + active plan tracker, writes
# `<repo>/.claude/session-context-summary.md` (cap 200 lines) so the
# UserPromptSubmit hook can inject a compact summary on every prompt.
#
# Refuses to start the session if:
#   - the tracker file referenced by ~/.claude/plans/.active-tracker
#     does not exist
#   - the summary file cannot be written
#
# Output (stdout) is shown to the agent as additionalContext.

set -euo pipefail

repo=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
[ -n "$repo" ] || exit 0
active_pointer="$repo/.claude/active-tracker"
if [ ! -f "$active_pointer" ]; then
    cat >&2 <<EOF
::error::ralph-loop-01: no active plan tracker registered.
Create one with:
  echo "$HOME/.claude/plans/<session>-tracker.md" > $active_pointer
  touch \$(cat $active_pointer)
Then re-open the session.
EOF
    exit 2
fi

tracker=$(<"$active_pointer")
if [ ! -f "$tracker" ]; then
    echo "[ralph-loop] active tracker '$tracker' missing - cannot load plan." >&2
    exit 2
fi
if ! grep -qE "^- \[[ xX~]\]" "$tracker" 2>/dev/null; then
    echo "::error::ralph-loop-01: active tracker '$tracker' has zero checkbox tasks." >&2
    exit 2
fi

repo=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
summary="$repo/.claude/session-context-summary.md"
mkdir -p "$(dirname "$summary")"

{
    echo "# Session context summary (auto-generated by ralph-loop hook 01)"
    echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    echo "## Active plan tracker"
    echo "Path: $tracker"
    echo
    echo '```'
    head -120 "$tracker"
    echo '```'
    echo
    echo "## Global rules excerpt"
    if [ -f "$HOME/.claude/CLAUDE.md" ]; then
        head -40 "$HOME/.claude/CLAUDE.md"
    fi
    echo
    echo "## Project rules (CLAUDE.md)"
    if [ -f "$repo/CLAUDE.md" ]; then
        head -40 "$repo/CLAUDE.md"
    fi
} | head -200 > "$summary"

cat <<EOF
[ralph-loop] context loaded. Tracker: $tracker
Open tasks:
$(grep -c "^- \[ \]" "$tracker" 2>/dev/null || echo 0)
Closed tasks:
$(grep -c "^- \[x\]" "$tracker" 2>/dev/null || echo 0)
Skipped tasks:
$(grep -c "\[SKIP\]" "$tracker" 2>/dev/null || echo 0)

Read $summary at session start. Do NOT end session while open tasks remain.
EOF

exit 0
